In [15]:
from bs4 import BeautifulSoup
import pandas as pd

input_file = 'instagram.html'

with open(input_file, 'r', encoding='utf-8') as f:
    contents = f.read()
    soup = BeautifulSoup(contents, "html.parser")
    # with span class <span class="_ap3a _aaco _aacu _aacx _aad7 _aade" dir="auto">
    
    # Find all <p> tags, get their text, and store it in a list
    divs_with_class = soup.find_all('div', class_='_a9zs')
    soup = BeautifulSoup(str(divs_with_class), 'html.parser')
    paragraphs_text = []
    for div in divs_with_class:
        # Find all <p> tags within the current div and get their text
        paragraphs = [p.get_text() for p in div.find_all('span', class_='_ap3a _aaco _aacu _aacx _aad7 _aade', dir='auto')]
        # Merge the text from multiple <p> tags into a single text block
        merged_paragraph = ' '.join(paragraphs)
        # Append the merged text to the list
        paragraphs_text.append(merged_paragraph)
    
# Print the list of text inside <p> tags
messages = []

import re

def filter_text(text):
    # Remove leading and trailing whitespace
    text = text.strip()
    
    # Remove HTML tags
    text = re.sub('<[^<]+?>', '', text)
    
    # Remove extra whitespace (including newlines)
    text = re.sub('\s+', ' ', text)
    
    return text
    
for text in paragraphs_text:
    if len(text) > 1:
        messages.append(filter_text(text))

In [16]:
msg_df = pd.DataFrame({'Message': messages, 'Sentiment': '-'})
i = 0
for msg in msg_df['Message']:
    print( msg)
    print()
    if i > 5: 
        break
    i += 1

Ringtone download from link in profile üôåüî•

We reached 5 million views !!! üôå thank you guys so much! Consider following me to support my work üí´

imagine if a family member dies and someone calls you

This is my ringtone bruhhhh

Okay, meu novo toque de celular.

Love itüíìüíì pls do tokyo ghoul

Literally now my ringtone

In [17]:
msg_df.head()

                                             Message Sentiment
0          Ringtone download from link in profile üôåüî•         -
1  We reached 5 million views !!! üôå thank you guy...         -
2  imagine if a family member dies and someone ca...         -
3                        This is my ringtone bruhhhh         -
4                   Okay, meu novo toque de celular.         -

In [24]:
df = pd.read_csv('Messages/messages.csv')

In [25]:
df.shape

(166, 2)

In [26]:
df

                                               Message Sentiment
0    He looks like such a friendly dude, it‚Äôs hard ...         -
1         In those movies, Willem was on a sabbatical.         -
2                             Yup he was being Da Foe.         -
3                                                Honey         -
4    Actors who play the worst villians are usually...         -
..                                                 ...       ...
161           Pronto, vai ser o toque do meu celular ‚ô°         -
162                                              üòçüòçüòçüòçüòç         -
163                                       @jd_pintason         -
164                                           @xo_cliq         -
165       Y'all didn't say this video is 24 hours long         -

[166 rows x 2 columns]

In [27]:
df_combined = pd.concat([df, msg_df], ignore_index=True)
df_combined_no_dup = df_combined.drop_duplicates()
df_combined_no_dup.reset_index(drop=True, inplace=True)

In [28]:
df_combined_no_dup

                                               Message Sentiment
0    He looks like such a friendly dude, it‚Äôs hard ...         -
1         In those movies, Willem was on a sabbatical.         -
2                             Yup he was being Da Foe.         -
3                                                Honey         -
4    Actors who play the worst villians are usually...         -
..                                                 ...       ...
161           Pronto, vai ser o toque do meu celular ‚ô°         -
162                                              üòçüòçüòçüòçüòç         -
163                                       @jd_pintason         -
164                                           @xo_cliq         -
165       Y'all didn't say this video is 24 hours long         -

[166 rows x 2 columns]

In [29]:
df_combined_no_dup.to_csv('Messages/messages.csv', index=False)