In [70]:
from bs4 import BeautifulSoup
import pandas as pd

input_file = 'instagram.html'

with open(input_file, 'r', encoding='utf-8') as f:
    contents = f.read()
    soup = BeautifulSoup(contents, "html.parser")
    # with span class <span class="_ap3a _aaco _aacu _aacx _aad7 _aade" dir="auto">
    
    # Find all <p> tags, get their text, and store it in a list
    divs_with_class = soup.find_all('div', class_='_a9zs')
    soup = BeautifulSoup(str(divs_with_class), 'html.parser')
    paragraphs_text = []
    for div in divs_with_class:
        # Find all <p> tags within the current div and get their text
        paragraphs = [p.get_text() for p in div.find_all('span', class_='_ap3a _aaco _aacu _aacx _aad7 _aade', dir='auto')]
        # Merge the text from multiple <p> tags into a single text block
        merged_paragraph = ' '.join(paragraphs)
        # Append the merged text to the list
        paragraphs_text.append(merged_paragraph)
    
# Print the list of text inside <p> tags
messages = []

import re

def filter_text(text):
    # Remove leading and trailing whitespace
    text = text.strip()
    
    # Remove HTML tags
    text = re.sub('<[^<]+?>', '', text)
    
    # Remove extra whitespace (including newlines)
    text = re.sub('\s+', ' ', text)
    
    return text
    
for text in paragraphs_text:
    if len(text) > 1:
        messages.append(filter_text(text))

<>:36: SyntaxWarning: invalid escape sequence '\s'
<>:36: SyntaxWarning: invalid escape sequence '\s'
C:\Users\nokap\AppData\Local\Temp\ipykernel_16396\914719144.py:36: SyntaxWarning: invalid escape sequence '\s'
  text = re.sub('\s+', ' ', text)

In [118]:
msg_df = pd.DataFrame({'Message': messages, 'Sentiment': 0, 'Message type hint': 'Positive: 0, 1: Negative'}) #, 'Message type hint': 'Positive: 0, 1: Negative'
i = 0
for msg in msg_df['Message']:
    print( msg)
    print()
    if i > 5: 
        break
    i += 1

Ringtone download from link in profile ðŸ™ŒðŸ”¥

We reached 5 million views !!! ðŸ™Œ thank you guys so much! Consider following me to support my work ðŸ’«

imagine if a family member dies and someone calls you

This is my ringtone bruhhhh

Okay, meu novo toque de celular.

Love itðŸ’“ðŸ’“ pls do tokyo ghoul

Literally now my ringtone

In [120]:
msg_df.head()

,Message,Sentiment,Message type hint
0,Ringtone download from link in profile ðŸ™ŒðŸ”¥,0,"Positive: 0, 1: Negative"
1,We reached 5 million views !!! ðŸ™Œ thank you guy...,0,"Positive: 0, 1: Negative"
2,imagine if a family member dies and someone ca...,0,"Positive: 0, 1: Negative"
3,This is my ringtone bruhhhh,0,"Positive: 0, 1: Negative"
4,"Okay, meu novo toque de celular.",0,"Positive: 0, 1: Negative"

In [127]:
df = pd.read_csv('Messages/messages.csv')

In [128]:
df.shape

(1117, 3)

In [129]:
df

,Message,Sentiment,Message type hint
0,"He looks like such a friendly dude, itâ€™s hard ...",0,"Positive: 0, 1: Negative"
1,"In those movies, Willem was on a sabbatical.",0,"Positive: 0, 1: Negative"
2,Yup he was being Da Foe.,0,"Positive: 0, 1: Negative"
3,Honey,0,"Positive: 0, 1: Negative"
4,Actors who play the worst villians are usually...,0,"Positive: 0, 1: Negative"
...,...,...,...
1112,"A good day to be in New Zealand, enjoying a ni...",0,"Positive: 0, 1: Negative"
1113,RIP anyone who bought all four physical versio...,0,"Positive: 0, 1: Negative"
1114,Absolutely flabbergasted. Canâ€™t believe Iâ€™ve b...,0,"Positive: 0, 1: Negative"
1115,Anyone else loving the anthology more than the...,0,"Positive: 0, 1: Negative"
1116,On first listen I like the vibe of the tracks ...,0,"Positive: 0, 1: Negative"

In [130]:
df_combined = pd.concat([df, msg_df], ignore_index=True)
df_combined_no_dup = df_combined.drop_duplicates()
df_combined_no_dup.reset_index(drop=True, inplace=True)

In [131]:
df_combined_no_dup

,Message,Sentiment,Message type hint
0,"He looks like such a friendly dude, itâ€™s hard ...",0,"Positive: 0, 1: Negative"
1,"In those movies, Willem was on a sabbatical.",0,"Positive: 0, 1: Negative"
2,Yup he was being Da Foe.,0,"Positive: 0, 1: Negative"
3,Honey,0,"Positive: 0, 1: Negative"
4,Actors who play the worst villians are usually...,0,"Positive: 0, 1: Negative"
...,...,...,...
1112,"A good day to be in New Zealand, enjoying a ni...",0,"Positive: 0, 1: Negative"
1113,RIP anyone who bought all four physical versio...,0,"Positive: 0, 1: Negative"
1114,Absolutely flabbergasted. Canâ€™t believe Iâ€™ve b...,0,"Positive: 0, 1: Negative"
1115,Anyone else loving the anthology more than the...,0,"Positive: 0, 1: Negative"
1116,On first listen I like the vibe of the tracks ...,0,"Positive: 0, 1: Negative"

In [132]:
df_combined_no_dup.to_csv('Messages/messages.csv', index=False)